version: "3.8"

services:

  auto_market_db:
    image: postgres
    container_name: project_db
    ports:
      - 15432:5432
    volumes:
      - ${MY_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


  auto_market_app:
    build:
      dockerfile: ./Dockerfile
    container_name: auto_market
    command: bash -c "python manage.py makemigrations && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - auto_market_db
    env_file:
      - .env

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  celery:
    container_name: celery
    build:
      dockerfile: ./Dockerfile
    command: celery -A root worker -l info
    env_file:
      - .env
    depends_on:
      - auto_market_app
      - auto_market_db
      - redis

  celery-beat:
    container_name: celery-beat
    build:
      dockerfile: ./Dockerfile
    command: celery -A root beat -l info
    env_file:
      - .env
    depends_on:
      - auto_market_app
      - auto_market_db
      - redis
      - celery
