version: "3.8"

services:

  auto_market_db:
    image: postgres
    container_name: project_db
    ports:
      - 15432:5432
    volumes:
      - ${MY_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


  auto_market_app:
    build:
      dockerfile: ./Dockerfile
    container_name: auto_market
    volumes:
      - static:/static
    ports:
      - 8000:8000
    depends_on:
      - auto_market_db
    env_file:
      - .env

  nginx:
    build:
      dockerfile: nginx/Dockerfile
    container_name: nginx
    volumes:
      - static:/static
    ports:
      - 180:80
    depends_on:
      - auto_market_app

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  celery:
    container_name: celery
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - auto_market_app
      - auto_market_db
      - redis

  celery-beat:
    container_name: celery-beat
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - auto_market_app
      - auto_market_db
      - redis
      - celery

volumes:
  static:
